export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';
export const FETCH_ITEM_REMOVE = 'FETCH_ITEM_REMOVE';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';

export const GET_TOP_TRACKS = 'GET_TOP_TRACKS';
export const GET_INFO_ARTIST = 'GET_INFO_ARTIST';
export const GET_SEARCH_TRACK = 'GET_SEARCH_TRACK';
export const FETCH_START = 'FETCH_START';
export const FETCH_ERROR = 'FETCH_ERROR';
